# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 'Dart (Build & Release)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - # â¬‡ï¸ Checkout source
      - uses: actions/checkout@v4

      # â¬‡ï¸ Setup Java (Android)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # â¬‡ï¸ Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
           channel: 'stable'
           architecture: x64

      # â¬‡ï¸ Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get

      # ğŸ”µ Build Android
      - name: Build Android APK
        run: |
          flutter build apk --release --split-per-abi

      # ğŸ”µ Build iOS (IPA)
      - name: Build iOS IPA
        run: |
          flutter build ipa --release --split-per-platform

      # ğŸ”µ Release to GitHub
      - name: Push to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*, build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN_FOR_GITHUB }}


